package org.restaurant.webservice;

import org.restaurant.webservice.order.buy.OrderRequest;
import org.restaurant.webservice.order.buy.OrderResponse;

import javax.jws.WebService;

/**
 * Created by jj.jimenez on 10/01/2017.
 */
@WebService(endpointInterface = "org.restaurant.webservice.OrderService", targetNamespace = "org.restaurant.webservice", serviceName = "OrderService") public class Order
   implements OrderService {

   @Override public OrderResponse doOrder(OrderRequest orderRequest) {
	  OrderResponse response = new OrderResponse();
	  response.setOrderId("AUTOGENERATED");
	  return response;
   }

   @Override public void doOrderTest(OrderRequest buyBagResquest) {
   }
}
